baseURL = "https://xiaoyvhuv.github.io"  # 网站的 URL
languageCode = "zh"  # 网站语言代码
title = "XingSiyv'sBlog"  # 网站标题
theme = "hugo-theme-ladder"  # 使用的主题名称
defaultContentLanguage = "zh"
enableEmoji = true

[params]
  brand = "主页"
  author = "I'm 邢思宇"
  authorDescription = "阅读｜思考｜产出｜进步"
  info = "相信相信的力量 | 不断探索"
  avatarURL = "images/xiaoyv.png"
  favicon = "images/xiaoyv.png"
  darkModeTheme = "data-dark-mode"

[languages]
  [languages.zh]
    languageName = "简体中文"
    weight = 1
    contentDir = "content/"
  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"

[params.options]
  showDarkMode = true

[[params.social]]
  name = "GitHub"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
  url = "https://github.com/xiaoyvhuv"

[[params.social]]
  name = "bilibili"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-tv"><rect x="2" y="7" width="20" height="15" rx="2" ry="2"></rect><polyline points="17 2 12 7 7 2"></polyline></svg>'
  url = "https://space.bilibili.com/672236811?spm_id_from=333.1007.0.0"

[params.analytics.umami]
  enable = true
  website_id = "ec55b2da-4f55-45ef-8aed-26e57078fd15"
  url = "https://umami-jlwf.vercel.app/hugo-ladder"

[[menu.main]]
  name = "文章"
  url = "/blog/"
  weight = 1
  
[[menu.main]]
  name = "项目"
  url = "/archive/"
  weight = 2

[[menu.main]]
  name = "联系"
  url = "/contact/"
  weight = 3


[[menu.main]]
  name = "网站统计"
  url = "https://umami-jlwf.vercel.app/share/ZKhEVgh56RlSfAMa/baize1998.github.io"
  weight = 4
